[options]
admin_passwd = $pbkdf2-sha512$600000$qtUao5TyPmdsjRFC6D2H0A$ZLYjLeUFafLiDL26z2wThPNjQonrLcrFR7RQLM.YgBtrqwKqHZvDd7xGjX/tqLul2jwZAf7IJi7VMz5wgfglPQ
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 3%xF*E1SjKuJ#EN!
addons_path = D:\odoo\odoo19\odoo19_dev\community\addons,D:\odoo\odoo19\odoo19_dev\community\odoo\addons,D:\odoo\odoo19\odoo19_dev\custom_addons
data_dir = D:\Odoo\Odoo19\odoo19_dev\data
db_template = template1
wkhtmltopdf = D:\wkhtmltopdf\bin\wkhtmltopdf.exe

